-- ─── Seed permission catalog for condominios ────────────────────────────────
-- One permission per tab. Keys follow the format: condominios.tab.<tab_id>
-- Idempotent via ON CONFLICT.

INSERT INTO public.permissions (key, category, label, description) VALUES
  -- Panel
  ('condominios.tab.panel',                 'panel', 'Panel principal',         'Panel de inicio'),
  ('condominios.tab.panel_directivo',       'panel', 'Panel directivo',         'Panel para junta directiva'),
  ('condominios.tab.cuadro_mando',          'panel', 'Cuadro de mando',         'Cuadro de mando integral'),
  ('condominios.tab.dashboard_ejecutivo',   'panel', 'Dashboard ejecutivo',     'KPIs ejecutivos'),
  ('condominios.tab.resumen_ejecutivo',     'panel', 'Resumen ejecutivo',       'Resumen ejecutivo'),
  ('condominios.tab.informe_ejecutivo',     'panel', 'Informe ejecutivo',       'Informe ejecutivo'),
  ('condominios.tab.informe_mensual',       'panel', 'Informe mensual',         'Informe mensual'),
  ('condominios.tab.indice_calidad',        'panel', 'Índice de calidad',       'Índice de calidad del servicio'),
  ('condominios.tab.dashboard_sostenibilidad','panel','Dashboard sostenibilidad','Dashboard de sostenibilidad'),
  ('condominios.tab.bitacora_actividad',    'panel', 'Bitácora actividad',      'Bitácora de actividad'),
  ('condominios.tab.gestor_alertas',        'panel', 'Gestor de alertas',       'Gestión de alertas'),
  ('condominios.tab.alertas',               'panel', 'Alertas',                 'Centro de alertas'),
  ('condominios.tab.centro_notificaciones', 'panel', 'Centro notificaciones',   'Centro de notificaciones'),
  ('condominios.tab.graficas_tendencias',   'panel', 'Gráficas tendencias',     'Gráficas y tendencias'),
  ('condominios.tab.metricas_servicio',     'panel', 'Métricas servicio',       'Métricas del servicio'),
  ('condominios.tab.bitacora_eventos',      'panel', 'Bitácora eventos',        'Bitácora de eventos'),
  ('condominios.tab.reportes',              'panel', 'Reportes',                'Reportes generales'),
  ('condominios.tab.kpis_financieros',      'panel', 'KPIs financieros',        'KPIs financieros'),
  ('condominios.tab.reporte_consolidado',   'panel', 'Reporte consolidado',     'Reporte consolidado'),

  -- Finanzas
  ('condominios.tab.cuotas',                'finanzas', 'Cuotas',               'Gestión de cuotas'),
  ('condominios.tab.generacion_cuotas',     'finanzas', 'Generación cuotas',    'Generación masiva de cuotas'),
  ('condominios.tab.plantillas_cuota',      'finanzas', 'Plantillas cuota',     'Plantillas de cuota'),
  ('condominios.tab.recargos_mora',         'finanzas', 'Recargos mora',        'Recargos por mora'),
  ('condominios.tab.reglas_mora',           'finanzas', 'Reglas mora',          'Reglas de mora'),
  ('condominios.tab.campanas_cobro',        'finanzas', 'Campañas cobro',       'Campañas de cobro'),
  ('condominios.tab.reporte_deudores',      'finanzas', 'Reporte deudores',     'Reporte de deudores'),
  ('condominios.tab.mapa_calor_cuotas',     'finanzas', 'Mapa calor cuotas',    'Mapa de calor de cuotas'),
  ('condominios.tab.conciliacion_cobros',   'finanzas', 'Conciliación cobros',  'Conciliación de cobros'),
  ('condominios.tab.estado_cuenta_residente','finanzas','Edo. cuenta residente','Estado de cuenta residente'),
  ('condominios.tab.estadocuenta',          'finanzas', 'Estado de cuenta',     'Estado de cuenta'),
  ('condominios.tab.convenios_cuota',       'finanzas', 'Convenios cuota',      'Convenios de cuota'),
  ('condominios.tab.plan_pago',             'finanzas', 'Plan de pago',         'Plan de pago'),
  ('condominios.tab.avisos_cobro',          'finanzas', 'Avisos de cobro',      'Avisos de cobro'),
  ('condominios.tab.cobranza',              'finanzas', 'Cobranza',             'Cobranza'),
  ('condominios.tab.cobranza_judicial',     'finanzas', 'Cobranza judicial',    'Cobranza judicial'),
  ('condominios.tab.presupuesto',           'finanzas', 'Presupuesto',          'Presupuesto'),
  ('condominios.tab.contabilidad',          'finanzas', 'Contabilidad',         'Contabilidad'),
  ('condominios.tab.comparativo_presupuesto','finanzas','Ppto. vs Real',        'Comparativo presupuesto'),
  ('condominios.tab.comparativo_anual',     'finanzas', 'Comparativo anual',    'Comparativo anual'),
  ('condominios.tab.pronostico_financiero', 'finanzas', 'Pronóstico financiero','Pronóstico financiero'),
  ('condominios.tab.simulador_cuotas',      'finanzas', 'Simulador cuotas',     'Simulador de cuotas'),
  ('condominios.tab.caja_chica',            'finanzas', 'Caja chica',           'Caja chica'),
  ('condominios.tab.gestion_fondo',         'finanzas', 'Gestión fondo',        'Gestión de fondo'),
  ('condominios.tab.fondo_reserva',         'finanzas', 'Fondo reserva',        'Fondo de reserva'),
  ('condominios.tab.tarifas',               'finanzas', 'Tarifas',              'Tarifas'),
  ('condominios.tab.cargos_adicionales',    'finanzas', 'Cargos adicionales',   'Cargos adicionales'),
  ('condominios.tab.recibos_digitales',     'finanzas', 'Recibos digitales',    'Recibos digitales'),
  ('condominios.tab.cierres',               'finanzas', 'Cierres',              'Cierres contables'),
  ('condominios.tab.cierre_anual',          'finanzas', 'Cierre anual',         'Cierre anual'),
  ('condominios.tab.historial_saldos',      'finanzas', 'Historial saldos',     'Historial de saldos'),
  ('condominios.tab.notificaciones_enviadas','finanzas','Notif. enviadas',      'Notificaciones enviadas'),
  ('condominios.tab.proformas',             'finanzas', 'Proformas',            'Proformas'),
  ('condominios.tab.exportacion',           'finanzas', 'Exportación',          'Exportación de datos'),
  ('condominios.tab.centro_costos',         'finanzas', 'Centro de costos',     'Centro de costos'),
  ('condominios.tab.analisis_cartera',      'finanzas', 'Análisis cartera',     'Análisis de cartera'),

  -- Residentes
  ('condominios.tab.tablero_ocupacion',     'residentes', 'Tablero ocupación',  'Tablero de ocupación'),
  ('condominios.tab.directorio_comunidad',  'residentes', 'Directorio comunidad','Directorio comunidad'),
  ('condominios.tab.directorio',            'residentes', 'Directorio',          'Directorio'),
  ('condominios.tab.arrendamientos',        'residentes', 'Arrendamientos',      'Arrendamientos'),
  ('condominios.tab.onboarding',            'residentes', 'Onboarding',          'Onboarding residente'),
  ('condominios.tab.entrega_unidad',        'residentes', 'Entrega unidad',      'Entrega de unidad'),
  ('condominios.tab.portal',                'residentes', 'Portal',              'Portal residente'),
  ('condominios.tab.resumen_residente',     'residentes', 'Resumen residente',   'Resumen residente'),
  ('condominios.tab.solicitudes',           'residentes', 'Solicitudes',         'Solicitudes'),
  ('condominios.tab.solicitudes_renta',     'residentes', 'Solicitudes renta',   'Solicitudes de renta'),
  ('condominios.tab.solicitudes_mudanza',   'residentes', 'Solicitudes mudanza', 'Solicitudes de mudanza'),
  ('condominios.tab.vehiculos',             'residentes', 'Vehículos',           'Vehículos'),
  ('condominios.tab.mascotas',              'residentes', 'Mascotas',            'Mascotas'),
  ('condominios.tab.accesos_res',           'residentes', 'Accesos residentes',  'Accesos de residentes'),
  ('condominios.tab.control_accesos_qr',    'residentes', 'Control QR',          'Control de accesos QR'),
  ('condominios.tab.certificados',          'residentes', 'Certificados',        'Certificados'),
  ('condominios.tab.manual_residente',      'residentes', 'Manual residente',    'Manual del residente'),
  ('condominios.tab.mapa_unidades',         'residentes', 'Mapa unidades',       'Mapa de unidades'),
  ('condominios.tab.scoring_unidades',      'residentes', 'Scoring unidades',    'Scoring de unidades'),

  -- Operaciones
  ('condominios.tab.mantenimiento',         'operaciones', 'Mantenimiento',      'Mantenimiento general'),
  ('condominios.tab.kanban_tickets',        'operaciones', 'Kanban tickets',     'Kanban de tickets'),
  ('condominios.tab.gantt_mantenimiento',   'operaciones', 'Gantt tickets',      'Gantt de mantenimiento'),
  ('condominios.tab.calendario_mantenimiento','operaciones','Calendario mant.',  'Calendario de mantenimiento'),
  ('condominios.tab.mant_preventivo',       'operaciones', 'Mant. preventivo',   'Mantenimiento preventivo'),
  ('condominios.tab.bitacora_manto',        'operaciones', 'Bitácora manto',     'Bitácora de mantenimiento'),
  ('condominios.tab.inventario',            'operaciones', 'Inventario',         'Inventario'),
  ('condominios.tab.suministros',           'operaciones', 'Suministros',        'Suministros'),
  ('condominios.tab.tareas_cond',           'operaciones', 'Tareas',             'Tareas del condominio'),
  ('condominios.tab.ordenes_compra',        'operaciones', 'Órdenes compra',     'Órdenes de compra'),
  ('condominios.tab.eval_proveedor',        'operaciones', 'Eval. proveedor',    'Evaluación de proveedores'),
  ('condominios.tab.proveedores',           'operaciones', 'Proveedores',        'Proveedores'),
  ('condominios.tab.obras',                 'operaciones', 'Obras',              'Obras'),
  ('condominios.tab.proyectos_cond',        'operaciones', 'Proyectos',          'Proyectos del condominio'),
  ('condominios.tab.permisos_obra',         'operaciones', 'Permisos obra',      'Permisos de obra'),
  ('condominios.tab.garantias',             'operaciones', 'Garantías',          'Garantías'),
  ('condominios.tab.checklist_areas',       'operaciones', 'Checklist áreas',    'Checklist de áreas'),
  ('condominios.tab.prog_limpieza',         'operaciones', 'Prog. limpieza',     'Programa de limpieza'),
  ('condominios.tab.control_plagas',        'operaciones', 'Control plagas',     'Control de plagas'),
  ('condominios.tab.prestamos',             'operaciones', 'Préstamos',          'Préstamos de equipo'),

  -- Instalaciones
  ('condominios.tab.amenidades',            'instalaciones', 'Amenidades',       'Amenidades'),
  ('condominios.tab.utilizacion_amenidades','instalaciones', 'Uso amenidades',   'Utilización de amenidades'),
  ('condominios.tab.parqueos',              'instalaciones', 'Parqueos',         'Parqueos'),
  ('condominios.tab.estac_visita',          'instalaciones', 'Estac. visita',    'Estacionamiento de visitas'),
  ('condominios.tab.bodegas',               'instalaciones', 'Bodegas',          'Bodegas'),
  ('condominios.tab.llaves',                'instalaciones', 'Llaves',           'Control de llaves'),
  ('condominios.tab.equipos',               'instalaciones', 'Equipos',          'Equipos'),
  ('condominios.tab.consumo_energia',       'instalaciones', 'Consumo energía',  'Consumo de energía'),
  ('condominios.tab.medidores_unidad',      'instalaciones', 'Medidores',        'Medidores por unidad'),
  ('condominios.tab.control_piscina',       'instalaciones', 'Piscina',          'Control de piscina'),
  ('condominios.tab.jardineria',            'instalaciones', 'Jardinería',       'Jardinería'),
  ('condominios.tab.elevadores',            'instalaciones', 'Elevadores',       'Elevadores'),
  ('condominios.tab.cisternas',             'instalaciones', 'Cisternas',        'Cisternas'),
  ('condominios.tab.generador',             'instalaciones', 'Generador',        'Generador eléctrico'),
  ('condominios.tab.incendio',              'instalaciones', 'Incendio',         'Sistema contra incendio'),
  ('condominios.tab.camaras',               'instalaciones', 'Cámaras',          'Cámaras de seguridad'),
  ('condominios.tab.gas',                   'instalaciones', 'Gas',              'Gas'),
  ('condominios.tab.integracion_agua',      'instalaciones', 'Integración agua', 'Integración con agua'),

  -- Seguridad
  ('condominios.tab.visitantes',            'seguridad', 'Visitantes',           'Visitantes'),
  ('condominios.tab.analisis_visitantes',   'seguridad', 'Análisis visitantes',  'Análisis de visitantes'),
  ('condominios.tab.vis_frecuentes',        'seguridad', 'Vis. frecuentes',      'Visitantes frecuentes'),
  ('condominios.tab.seguridad',             'seguridad', 'Seguridad',            'Seguridad general'),
  ('condominios.tab.rutas_ronda',           'seguridad', 'Rutas ronda',          'Rutas de ronda'),
  ('condominios.tab.plantillas_cargo',      'seguridad', 'Plantillas cargo',     'Plantillas de cargo'),
  ('condominios.tab.tareas_personal',       'seguridad', 'Tareas personal',      'Tareas de personal'),
  ('condominios.tab.revision_tareas',       'seguridad', 'Revisión tareas',      'Revisión de tareas'),
  ('condominios.tab.desempeno_personal',    'seguridad', 'Desempeño personal',   'Desempeño de personal'),
  ('condominios.tab.paqueteria',            'seguridad', 'Paquetería',           'Paquetería'),
  ('condominios.tab.objetos',               'seguridad', 'Objetos perdidos',     'Objetos perdidos'),
  ('condominios.tab.incidentes',            'seguridad', 'Incidentes',           'Incidentes'),
  ('condominios.tab.reclamos',              'seguridad', 'Reclamos',             'Reclamos'),
  ('condominios.tab.bitacora_guardia',      'seguridad', 'Bitácora guardia',     'Bitácora de guardia'),
  ('condominios.tab.presencia',             'seguridad', 'Presencia',            'Control de presencia'),
  ('condominios.tab.panel_turno',           'seguridad', 'Panel turno',          'Panel de turno'),
  ('condominios.tab.emergencias',           'seguridad', 'Emergencias',          'Emergencias'),

  -- Comunidad
  ('condominios.tab.comunidad',             'comunidad', 'Comunidad',            'Comunidad'),
  ('condominios.tab.infracciones',          'comunidad', 'Infracciones',         'Infracciones'),
  ('condominios.tab.sanciones',             'comunidad', 'Sanciones',            'Sanciones'),
  ('condominios.tab.gestion_conflictos',    'comunidad', 'Conflictos',           'Gestión de conflictos'),
  ('condominios.tab.asambleas',             'comunidad', 'Asambleas',            'Asambleas'),
  ('condominios.tab.asamblea_digital',      'comunidad', 'Asamblea digital',     'Asamblea digital'),
  ('condominios.tab.votaciones',            'comunidad', 'Votaciones',           'Votaciones'),
  ('condominios.tab.junta',                 'comunidad', 'Junta',                'Junta directiva'),
  ('condominios.tab.actas',                 'comunidad', 'Actas',                'Actas'),
  ('condominios.tab.acuerdos',              'comunidad', 'Acuerdos',             'Acuerdos'),
  ('condominios.tab.eventos_comunidad',     'comunidad', 'Eventos comunidad',    'Eventos de la comunidad'),
  ('condominios.tab.agenda',                'comunidad', 'Agenda',               'Agenda'),
  ('condominios.tab.cumpleanos',            'comunidad', 'Cumpleaños',           'Cumpleaños'),
  ('condominios.tab.programa_actividades',  'comunidad', 'Programa actividades', 'Programa de actividades'),
  ('condominios.tab.buzon_sugerencias',     'comunidad', 'Buzón sugerencias',    'Buzón de sugerencias'),
  ('condominios.tab.encuestas',             'comunidad', 'Encuestas',            'Encuestas'),
  ('condominios.tab.encuesta_dashboard',    'comunidad', 'Dashboard encuestas',  'Dashboard de encuestas'),
  ('condominios.tab.comunicados',           'comunidad', 'Comunicados',          'Comunicados'),
  ('condominios.tab.recordatorios',         'comunidad', 'Recordatorios',        'Recordatorios'),
  ('condominios.tab.comunicacion_condominios','comunidad','Comunicación',        'Comunicación de condominios'),

  -- Administración
  ('condominios.tab.documentos',            'administracion', 'Documentos',      'Documentos'),
  ('condominios.tab.reglamento',            'administracion', 'Reglamento',      'Reglamento'),
  ('condominios.tab.firmas',                'administracion', 'Firmas',          'Firmas digitales'),
  ('condominios.tab.personal',              'administracion', 'Personal',        'Personal'),
  ('condominios.tab.capacitacion_personal', 'administracion', 'Capacitación',    'Capacitación de personal'),
  ('condominios.tab.correspondencia',       'administracion', 'Correspondencia', 'Correspondencia'),
  ('condominios.tab.libro_novedades',       'administracion', 'Libro novedades', 'Libro de novedades'),
  ('condominios.tab.notas_admin',           'administracion', 'Notas admin',     'Notas administrativas'),
  ('condominios.tab.reg_autoridades',       'administracion', 'Reg. autoridades','Registro de autoridades'),
  ('condominios.tab.bitacora_acciones',     'administracion', 'Bitácora acciones','Bitácora de acciones'),
  ('condominios.tab.vencimientos_criticos', 'administracion', 'Vencimientos',    'Vencimientos críticos'),
  ('condominios.tab.polizas',               'administracion', 'Pólizas',         'Pólizas de seguro'),
  ('condominios.tab.inspecciones',          'administracion', 'Inspecciones',    'Inspecciones'),
  ('condominios.tab.propuestas',            'administracion', 'Propuestas',      'Propuestas'),
  ('condominios.tab.memoria',               'administracion', 'Memoria',         'Memoria de labores'),
  ('condominios.tab.automatizaciones',      'administracion', 'Automatizaciones','Automatizaciones'),
  ('condominios.tab.plantillas_mensaje',    'administracion', 'Plantillas msj',  'Plantillas de mensajes'),
  ('condominios.tab.flujo_aprobacion',      'administracion', 'Flujo aprobación','Flujo de aprobación'),
  ('condominios.tab.envio_masivo',          'administracion', 'Envío masivo',    'Envío masivo'),
  ('condominios.tab.notificaciones',        'administracion', 'Notificaciones',  'Notificaciones'),
  ('condominios.tab.configuracion_cond',    'administracion', 'Config. cond.',   'Configuración del condominio'),
  ('condominios.tab.configuracion',         'administracion', 'Configuración',   'Configuración'),
  ('condominios.tab.multi_condominio',      'administracion', 'Multi condominio','Multi-condominio'),

  -- Especiales
  ('condominios.tab.str',                   'especiales', 'STR (renta corta)',   'Short-term rentals'),
  ('condominios.tab.locales',               'especiales', 'Locales',             'Locales comerciales'),
  ('condominios.tab.housekeeping',          'especiales', 'Housekeeping',        'Housekeeping'),
  ('condominios.tab.concierge',             'especiales', 'Concierge',           'Concierge'),
  ('condominios.tab.residuos',              'especiales', 'Residuos',            'Gestión de residuos'),
  ('condominios.tab.sostenibilidad',        'especiales', 'Sostenibilidad',      'Sostenibilidad')
ON CONFLICT (key) DO NOTHING;
